VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME = ""
ORG_URL = ""
ORG_LOGO = ""
ORG_DESCRIPTION = ""

[[CURRENCIES]]
code = ""
name = ""
issuer = ""
is_asset_anchored = false
display_decimals = 7
desc = ""
image = ""
conditions = ""
